export const ADD_COMMENT = "ADD_COMMENT";
export const DISHES_LOADING ="DISHES_LOADING";
export const DISHES_FAILED ="DISHES_FAILED";
export const ADD_DISHES ="ADD_DISHES";
// export const LEADERS_LOADING ="LEADERS_LOADING";
// export const PROMOTIONS_LOADING="PROMOTIONS_LOADING";
// export const COMMENTS_LOADING ="COMMENTS_LOADING";